name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Linux-amd64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


  Linux-arm:
    runs-on: ubuntu-latest-arm

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
